# WSI Patch Filter Configuration File
# This file contains all configurable parameters for the WSI patch filtering pipeline

# Dataset parameters
dataset_name: "tcga-brca"  # Dataset name for output naming

# WSI filtering parameters
accept_label: ["IDC", "ILC"]  # Labels to be balanced
accept_hosp_list: ["AR", "A2", "D8", "BH"]  # Only accept these hospital sources
n_per_hosp: 10  # Number of WSIs to select per hospital
num_sampled_patches: 100  # Maximum number of patches per WSI
patch_size: 256  # Size of extracted patches

# Additional filtering conditions (set to null for no filtering)
accept_age_groups: ["60-69", "70-79"]  # Age groups to accept (null for all)
accept_gender: ["female"]  # Gender to accept (null for all)
accept_race: ["white"]  # Race to accept (null for all)

# Path configuration
coord_dir: "/raid/mengliang/wsi_process/tcga-brca_patch/patches/"  # Directory containing patch coordinates
wsi_dir: "/home/mxz3935/dataset_folder/tcga-brca/"  # Directory containing WSI files
label_file: "files/tcga-brca_label.csv"  # Path to label CSV file

# CONCH model parameters
checkpoint_path: "./checkpoints/conch/pytorch_model.bin"  # Path to CONCH model checkpoint
model_cfg: "conch_ViT-B-16"  # CONCH model configuration
probability_threshold: 0.8  # Probability threshold for patch filtering

# Zero-shot classification parameters
classes: ["invasive ductal carcinoma", "invasive lobular carcinoma", "normal breast tissue"]  # Class names for classification
prompts: ["an H&E image of invasive ductal carcinoma", "an H&E image of invasive lobular carcinoma","an H&E image of normal breast tissue"]  # Text prompts for zero-shot classification

# Label mapping from model prediction to standard labels
label_map:
  "invasive ductal carcinoma": "IDC"
  "invasive lobular carcinoma": "ILC"
  "normal breast tissue": "NORMAL" 

# Example configurations for different datasets:
#
# For TCGA-LUAD:
# dataset_name: "tcga-luad"
# accept_label: ["LUAD"]
# coord_dir: "/raid/mengliang/wsi_process/tcga-luad_patch/patches/"
# wsi_dir: "/home/mxz3935/dataset_folder/tcga-luad/"
# label_file: "files/tcga-luad_label.csv"
# classes: ["lung adenocarcinoma", "normal lung tissue"]
# prompts: ["an H&E image of lung adenocarcinoma", "an H&E image of normal lung tissue"]
# label_map:
#   "lung adenocarcinoma": "LUAD"
#   "normal lung tissue": "NORMAL" 